title: API Reference
preserve_directory_names: true 
flatten_single_child_sections: true 
ignore: "*.hidden.md" 
sort:
  direction: asc 
  type: natural 
  by: filename 
  sections: last 
  ignore_case: true 

append_unmatched: true 
use_index_title: true 
