title: Overview
preserve_directory_names: true 
hide: true 
flatten_single_child_sections: true 
ignore: "*.hidden.md" 
sort:
  direction: asc 
  type: natural 
  by: filename 
  sections: last 
  ignore_case: true 

nav: 
  - Overview: README.md
  - Installation: installation_docs/index_installation.md

  - User's Hub: 
    - Overview: user_docs/index_user.md
    - Main Configuration: user_docs/configuration_main.md
    - Operational Configuration: user_docs/configuration_operational.md
    - Examples: user_docs/examples
  - Developer's Hub: developer_docs

append_unmatched: true 
use_index_title: true 
